<?php

use CodeIgniter\Database\Migration;

class SiteStats extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'site_stat_id' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
            ],
            'ip_address' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
            ],
            'device_type' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'browser_type' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'page_type' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'page_visited_id' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'page_visited_url' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'referrer' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'status_code' => [
                'type' => 'INT',
                'null' => true,
            ],
            'user_id' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'session_id' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'request_method' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'operating_system' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'country' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'screen_resolution' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'user_agent' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'other_params' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
        ]);
        $this->forge->addKey('site_stat_id', true);
        $this->forge->createTable('site_stats');

        //Insert default record
        $data = [
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "192.168.1.1",
                'device_type' => "mobile",
                'browser_type' => "Safari",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/about"),
                'referrer' => "POST",
                'status_code' => 201,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID("session-" . uniqid()),
                'request_method' => "POST",
                'operating_system' => "iOS",
                'country' => "UK",
                'screen_resolution' => "375 x 812",
                'user_agent' => "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1",
                'other_params' => json_encode(['source' => 'direct']),
                'created_at' => date('Y-m-d H:i:s')
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "10.0.0.1",
                'device_type' => "tablet",
                'browser_type' => "Firefox",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/contact"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "172.16.0.1",
                'device_type' => "mobile",
                'browser_type' => "Edge",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "POST",
                'status_code' => 204,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "192.168.2.1",
                'device_type' => "mobile",
                'browser_type' => "Opera",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/blog"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-4 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) OPT/15.6",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-5 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36 Edge/130.0.0.0",
                'other_params' => null,
                'created_at' => date('Y-m-d H:i:s', strtotime('-6 day'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-1 month'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-2 months'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-3 months'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-3 months'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-4 months'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-5 months'))
            ],
            [
                'site_stat_id' => getGUID(),
                'ip_address' => "102.129.135.0",
                'device_type' => "desktop",
                'browser_type' => "Google Chrome",
                'page_type' => "Page",
                'page_visited_id' => getGUID(),
                'page_visited_url' => base_url("/"),
                'referrer' => "GET",
                'status_code' => 200,
                'user_id' => getGUID(getDefaultAdminGUID()),
                'session_id' => getGUID(),
                'request_method' => "GET",
                'operating_system' => "Windows",
                'country' => "US",
                'screen_resolution' => "1280 x 591",
                'user_agent' => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
                'other_params' => null,
                'created_at' => date('Y-m-01 00:00:00', strtotime('-6 months'))
            ]
        ];

        // Using Query Builder
        $this->db->table('site_stats')->insertBatch($data);
    }

    public function down()
    {
        $this->forge->dropTable('site_stats');
    }
}
