name: 🚀 Deploy website on push
on:
  push:
    branches: [main]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.ignitercms.com
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          timeout: 120000
          server-dir: /
          # 👇 Add the exclude parameter here
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            install/database.sql
            original-code/**
            refactored-code/**
